name: Build and test ArUco detection

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: aruco
    strategy:
      matrix:
        compiler: [g++, clang++]
        build_type: [Debug, Release]
    steps:
    - uses: actions/checkout@v4
    - name: Configure ${{ matrix.compiler }} ${{ matrix.build_type }}
      run: cmake -S . -B build-${{ matrix.compiler }}-${{ matrix.build_type }} -GNinja -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    - name: Build ${{ matrix.compiler }} ${{ matrix.build_type }}
      run: ninja -C build-${{ matrix.compiler }}-${{ matrix.build_type }}
    - name: Test ${{ matrix.compiler }} ${{ matrix.build_type }}
      run: ctest --output-on-failure --test-dir build-${{ matrix.compiler }}-${{ matrix.build_type }}
